from exs_shell.register.events.base import event
from exs_shell.register.events.connectors import (
    niri,
    option,
    tray,
    cava,
    poll,
    systemd_session,
    systemd_system,
    audio,
    upower,
    network,
    bluetooth,
    backlight,
    power_profiles,
    notifications,
    battery,
    applications,
    key_kontroller,
    window,
    mpris,
)


__all__ = [
    "event",
    "niri",
    "option",
    "tray",
    "cava",
    "poll",
    "systemd_session",
    "systemd_system",
    "audio",
    "upower",
    "network",
    "bluetooth",
    "backlight",
    "power_profiles",
    "notifications",
    "battery",
    "applications",
    "key_kontroller",
    "window",
    "mpris",
]
