from enum import StrEnum


class UIIcons(StrEnum):
    WINDOW_CLOSE = ""
    QUESTION = ""
    HEADSET = "󰋎"
    HEADPHONES = "󰋋"
    PHONE = "󰏲"
    WATCH = ""
    KEYBOARD = ""
    MOUSE = ""
    LOCK = ""
    TV = ""
    DESKTOP = ""
    MAIN = ""
    PRINTER = "󰐪"
    CAMERA = ""
    SPEAKERS = "󰓃"
    PACKAGE = ""
    SEARCH = ""
    SYSTEM = ""
    BLUETOOTH = "󰂯"
    INFO = ""
    PALLETTE = "󰏘"
    INTERFACE = ""
    SLINE = ""
    LOCATION = ""
    SLEEP = "󰒲"
    SHOW = "󰈉"
    TEMPERATURE = ""
    SERVICES = ""
    NOTIFICATIONS = "󰂚"
    ARC = ""
    UP = ""
    DEVICES = ""
    REFRESH = ""
    DOWN = ""
    LEFT = ""
    RIGHT = ""
    POWER = ""
    MIC = ""
    OPEN_IN_WINDOW = ""
    DARK = "󰃜"
    WEATHER = "󰖑"
    OSD = ""
