from enum import StrEnum


class UIIcons(StrEnum):
    WINDOW_CLOSE = ""
    QUESTION = ""
    HEADSET = "󰋎"
    HEADPHONES = "󰋋"
    PHONE = "󰏲"
    WATCH = ""
    KEYBOARD = ""
    MOUSE = ""
    TV = ""
    PRINTER = "󰐪"
    CAMERA = ""
    SPEAKERS = "󰓃"
    PACKAGE = ""
    SEARCH = ""
    SYSTEM = ""
    APPEARANCE = "󰏘"
    BLUETOOTH = "󰂯"
    SERVICES = ""
    INFO = ""
    INTERFACE = ""
    SLINE = ""
    ARC = ""
    UP = ""
    DOWN = ""
    LEFT = ""
    RIGHT = ""
    POWER = ""
    MIC = ""
    OPEN_IN_WINDOW = ""
    DARK = "󰃜"
