from typing import Protocol

from ignis.base_widget import BaseWidget
from ignis.widgets import Revealer as IgnisRevealer

from exs_shell.ui.widgets.windows import Revealer


class IWindow(Protocol):
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def child(self) -> BaseWidget: ...
    @child.setter
    def child(self, value: BaseWidget): ...
    @property
    def revealer(self) -> Revealer | IgnisRevealer: ...
    @revealer.setter
    def revealer(self, value: Revealer | IgnisRevealer): ...
    def set_visible(self, value: bool): ...
